name: Update Google Scholar Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *' # 触发时间：每天08:00 UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update stats
      run: |
        # 在这里添加更新统计数据的脚本命令
        # 例如，下载 gs_data.json 并将其复制到 google-scholar-stats 分支

    - name: Commit and push changes
      run: |
        git config --local user.name "Your GitHub Username"
        git config --local user.email "your.email@example.com"
        git commit -am "Update Google Scholar stats"
        git push origin google-scholar-stats
